name: Update shared CI files
'on':
  workflow_dispatch:  # Allow to run manually
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 02:00
jobs:
  call-update-workflow:
    uses: chmeliik-rhtap/task-repo-shared-ci/.github/workflows/update-shared-ci.yaml@main
    secrets:
      SHARED_CI_UPDATER_APP_ID: ${{ secrets.SHARED_CI_UPDATER_APP_ID }}
      SHARED_CI_UPDATER_PRIVATE_KEY: ${{ secrets.SHARED_CI_UPDATER_PRIVATE_KEY }}
