name: Update shared CI files
'on':
  workflow_dispatch:  # Allow to run manually
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 02:00
jobs:
  call-update-workflow:
    uses: chmeliik-rhtap/task-repo-shared-ci/.github/workflows/update-shared-ci.yaml@main
